# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

warning_are_errors: true
bioc_check: true

r:
# - release
- devel
- bioc-devel

r_check_args: --no-build-vignettes --no-vignettes

after_success:
  - Rscript -e 'library(covr);codecov()'
